name: "MultiEvent Pipeline"

on:
    push:
        branches:
            - master
            - test
    pull_request: 
        branches: 
            - master
            - test
    workflow_dispatch: 


jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
        - name: "Running On master/test Push"
          run: echo "Running On master/test Push"

    on-pull-request:
        if: github.event_name =='pull_request'
        runs-on: ubuntu-latest
        steps:
        - name: "Running On Pull request"
          run: echo "Running On Pull request"
    
    on-workflow-dispatch:
        if: github.event_name =='workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
        - name: "Running On workflow dispatch"
          run: echo "Running On workflow_dispatch"